# Generated by Django 5.2.5 on 2025-11-09 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventoacceso',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='eventoacceso',
            name='visto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventoacceso',
            name='resultado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventoacceso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_acceso', to=settings.AUTH_USER_MODEL),
        ),
    ]
